@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

String version  = "{{{ .major }}}.{{{ .minor }}}.{{{ .patch }}}"
String imageTag = "v" + version

olcnePipeline(
        branchPattern: new BranchPattern(master: 'oracle/release/' + version, feature: '(?!^release/.*$)(^.*$)'),
        containers: [('container-registry.oracle.com/olcne/configmap-reload:' + imageTag ): 'olcne/configmap-reload:' + imageTag],
        platforms: [ 'ol8'],
        architectures: ['x86_64', 'aarch64'],
        yumOL8Repos: ['ol8_appstream']
)
